import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "James Hardie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
    <body className={inter.className}>
      
     <div className=" w-full flex items-center justify-evenly z-[999999999] fixed top-0"> 
     <Navbar/>
     </div>
     <div className="mt-32">

      {children}
     </div>
      </body>
  </html>
  );
}
